services:
  relay-a:
    build:
      context: ../relay
    ports:
      - "8001:8000"
    environment:
      RELAY_SHARD_ID: "0"

  relay-b:
    build:
      context: ../relay
    ports:
      - "8002:8000"
    environment:
      RELAY_SHARD_ID: "1"

  relay-c:
    build:
      context: ../relay
    ports:
      - "8003:8000"
    environment:
      RELAY_SHARD_ID: "2"
